# ReadTheDocs configuration file version.
version: 2

sphinx:
    configuration: docs/source/conf.py

build:
    os: ubuntu-20.04
    tools:
        python: "3.11"

python:
    install:
        - method: pip
          path: .
          extra_requirements:
              - dev
