# ReadTheDocs configuration file version.
version: 2

sphinx:
    configuration: docs/conf.py

build:
    tools:
        python: "3.9"

python:
    install:
        - requirements: docs/development_requirements.txt
    system_packages: true
