name: build_wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: build_wheels_on_${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-latest-xlarge]

    steps:
      - uses: actions/checkout@v4

      - name: build_wheels
        uses: pypa/cibuildwheel@v2.16.3

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl